// <auto-generated>
// This code was generated by the Pulsar Rule Compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Pulsar.Runtime.Engine;
using Pulsar.Runtime.Storage;
using Pulsar.Models.Actions;
using Serilog;

namespace Pulsar.CompiledRules
{
    public class CompiledRuleEngine : IRuleEngine
    {
        private readonly IDataStore _dataStore;
        private readonly IActionExecutor _actionExecutor;
        private readonly ILogger _logger;

        public CompiledRuleEngine(
            IDataStore dataStore,
            IActionExecutor actionExecutor,
            ILogger logger)
        {
            _dataStore = dataStore;
            _actionExecutor = actionExecutor;
            _logger = logger.ForContext<CompiledRuleEngine>();
        }

        public async Task ExecuteCycleAsync()
        {
            var data = await _dataStore.GetCurrentDataAsync();

            // Layer 0
            _logger.Debug("Executing rules in layer 0");
            _logger.Debug("Evaluating HighTemperatureAlert in layer 0");
            await EvaluateHighTemperatureAlertAsync(data);
            _logger.Debug("Evaluating HumidityPressureCheck in layer 0");
            await EvaluateHumidityPressureCheckAsync(data);
            _logger.Debug("Evaluating TemperatureConversion in layer 0");
            await EvaluateTemperatureConversionAsync(data);

            // Layer 1
            _logger.Debug("Executing rules in layer 1");
            _logger.Debug("Evaluating SystemStatusUpdate in layer 1");
            await EvaluateSystemStatusUpdateAsync(data);

        }

        private async Task EvaluateHighTemperatureAlertAsync(IDictionary<string, double> data)
        {
            _logger.Debug("Evaluating rule HighTemperatureAlert");

            bool conditionMet = false;
            try
            {
            conditionMet = true;
            var thresholdResult = await _dataStore.CheckThresholdOverTimeAsync(
                "temperature",
                50,
                TimeSpan.FromMilliseconds(500));
            conditionMet = thresholdResult;
            if (!conditionMet) return;
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Error evaluating rule HighTemperatureAlert");
                return;
            }

            if (conditionMet)
            {
                _logger.Information("Rule HighTemperatureAlert conditions met, executing actions");
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "alerts:temperature",
                        Value = 1
                    }
                });
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SendMessage = new Pulsar.Models.Actions.SendMessageAction
                    {
                        Channel = "alerts",
                        Message = "Temperature too high!"
                    }
                });
            }
        }

        private async Task EvaluateHumidityPressureCheckAsync(IDictionary<string, double> data)
        {
            _logger.Debug("Evaluating rule HumidityPressureCheck");

            bool conditionMet = false;
            try
            {
            conditionMet = false;
            bool subConditionMet0 = true;
            conditionMet = conditionMet || subConditionMet0;
            bool subConditionMet1 = true;
            conditionMet = conditionMet || subConditionMet1;
            if (!conditionMet) return;
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Error evaluating rule HumidityPressureCheck");
                return;
            }

            if (conditionMet)
            {
                _logger.Information("Rule HumidityPressureCheck conditions met, executing actions");
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "alerts:humidity",
                        Value = 1
                    }
                });
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "alerts:pressure",
                        Value = 1
                    }
                });
            }
        }

        private async Task EvaluateTemperatureConversionAsync(IDictionary<string, double> data)
        {
            _logger.Debug("Evaluating rule TemperatureConversion");

            bool conditionMet = false;
            try
            {
            conditionMet = true;
            if (!data.TryGetValue("temperature", out var value_temp))
            {
                _logger.Warning("Data source temperature not found");
                conditionMet = false;
                return;
            }
            await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
            {
                SetValue = new Pulsar.Models.Actions.SetValueAction
                {
                    Key = "converted_temp",
                    Value = (value_temp - 32.0) * (5.0 / 9.0)
                }
            });
            conditionMet = (value_temp - 32.0) * (5.0 / 9.0) > 25.0;
            if (!conditionMet) return;
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Error evaluating rule TemperatureConversion");
                return;
            }

            if (conditionMet)
            {
                _logger.Information("Rule TemperatureConversion conditions met, executing actions");
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "converted_temp",
                        Value = (data["temperature"] - 32.0) * (5.0 / 9.0)
                    }
                });
            }
        }

        private async Task EvaluateSystemStatusUpdateAsync(IDictionary<string, double> data)
        {
            _logger.Debug("Evaluating rule SystemStatusUpdate");

            bool conditionMet = false;
            try
            {
                // Check if any alerts are active
                if (!data.TryGetValue("alerts:temperature", out var tempAlert) ||
                    !data.TryGetValue("alerts:humidity", out var humidityAlert) ||
                    !data.TryGetValue("alerts:pressure", out var pressureAlert))
                {
                    _logger.Warning("One or more alert values not found");
                    return;
                }

                conditionMet = tempAlert > 0 || humidityAlert > 0 || pressureAlert > 0;
                _logger.Debug(
                    "Alert status - Temperature: {TempAlert}, Humidity: {HumidityAlert}, Pressure: {PressureAlert}",
                    tempAlert,
                    humidityAlert,
                    pressureAlert
                );
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Error evaluating rule SystemStatusUpdate");
                return;
            }

            if (conditionMet)
            {
                _logger.Information("Rule SystemStatusUpdate conditions met, executing actions");
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "system:status",
                        Value = "alert"
                    }
                });
            }
            else
            {
                _logger.Information("No alerts active, setting normal status");
                await _actionExecutor.ExecuteAsync(new Pulsar.Models.Actions.CompiledRuleAction
                {
                    SetValue = new Pulsar.Models.Actions.SetValueAction
                    {
                        Key = "system:status",
                        Value = "normal"
                    }
                });
            }
        }

    }
}
