version: 1
validSensors:
  - input:temperature
  - input:humidity
  - input:pressure
  - output:high_temperature
  - output:temperature_rising
  - output:heat_index
  - output:heat_alert
  - output:impossible_condition
  - output:storm_approaching
  - output:emergency_alert
  - buffer:temp_history
cycleTime: 100
redis:
  endpoints:
    - localhost:6379
  poolSize: 4
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: false
bufferCapacity: 100
