using System.Text;
using Pulsar.Models;
using Pulsar.Models.Actions;
using Pulsar.RuleDefinition.Models;
using Serilog;
using Pulsar.Runtime.Engine;

namespace Pulsar.Compiler.CodeGeneration;

/// <summary>
/// Generates C# code from compiled rules
/// </summary>
public class RuleCodeGenerator
{
    private readonly ILogger _logger;
    private readonly string _namespace;

    public RuleCodeGenerator(ILogger logger, string @namespace = "Pulsar.CompiledRules")
    {
        _logger = logger.ForContext<RuleCodeGenerator>();
        _namespace = @namespace;
    }

    public string GenerateCode(CompiledRuleSet ruleSet)
    {
        var sb = new StringBuilder();

        // Add header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by the Pulsar Rule Compiler.");
        sb.AppendLine("// Do not modify this file directly.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Add usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Pulsar.Runtime.Engine;");
        sb.AppendLine();

        // Begin namespace
        sb.AppendLine($"namespace {_namespace}");
        sb.AppendLine("{");

        // Generate CompiledRuleEngine class
        sb.AppendLine("    public class CompiledRuleEngine : IRuleEngine");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IDataStore _dataStore;");
        sb.AppendLine("        private readonly IActionExecutor _actionExecutor;");
        sb.AppendLine("        private readonly ILogger _logger;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("        public CompiledRuleEngine(");
        sb.AppendLine("            IDataStore dataStore,");
        sb.AppendLine("            IActionExecutor actionExecutor,");
        sb.AppendLine("            ILogger logger)");
        sb.AppendLine("        {");
        sb.AppendLine("            _dataStore = dataStore;");
        sb.AppendLine("            _actionExecutor = actionExecutor;");
        sb.AppendLine("            _logger = logger.ForContext<CompiledRuleEngine>();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate ExecuteCycle method
        sb.AppendLine("        public async Task ExecuteCycleAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            var data = await _dataStore.GetCurrentDataAsync();");
        sb.AppendLine();

        // Generate code for each layer
        for (int layer = 0; layer < ruleSet.LayerCount; layer++)
        {
            var layerRules = ruleSet.Rules
                .Where(r => r.Layer == layer)
                .OrderBy(r => r.Rule.Name) // Ensure deterministic ordering within layer
                .ToList();

            if (layerRules.Any())
            {
                sb.AppendLine($"            // Layer {layer}");
                sb.AppendLine($"            _logger.Debug(\"Executing rules in layer {layer}\");");

                foreach (var rule in layerRules)
                {
                    sb.AppendLine($"            _logger.Debug(\"Evaluating {rule.Rule.Name} in layer {layer}\");");
                    sb.AppendLine($"            await Evaluate{rule.Rule.Name}Async(data);");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("            await _actionExecutor.ExecutePendingActionsAsync();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate individual rule evaluation methods
        foreach (var rule in ruleSet.Rules)
        {
            GenerateRuleMethod(sb, rule);
        }

        // Close class and namespace
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateRuleMethod(StringBuilder sb, CompiledRule rule)
    {
        sb.AppendLine($"        private async Task Evaluate{rule.Rule.Name}Async(IDictionary<string, double> data)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.Debug(\"Evaluating rule {rule.Rule.Name}\");");
        sb.AppendLine();

        // Generate condition evaluation
        sb.AppendLine("            bool conditionMet = false;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        GenerateConditionCode(sb, rule.Rule.Conditions);
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                _logger.Error(ex, \"Error evaluating rule {rule.Rule.Name}\");");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Generate action execution
        sb.AppendLine("            if (conditionMet)");
        sb.AppendLine("            {");
        sb.AppendLine($"                _logger.Information(\"Rule {rule.Rule.Name} conditions met, executing actions\");");
        foreach (var action in rule.Rule.Actions)
        {
            GenerateActionCode(sb, action);
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void GenerateConditionCode(StringBuilder sb, ConditionGroup conditions)
    {
        if (conditions.All != null && conditions.All.Any())
        {
            sb.AppendLine("            conditionMet = true;");
            foreach (var condition in conditions.All)
            {
                GenerateConditionEvaluation(sb, condition);
                sb.AppendLine("            if (!conditionMet) break;");
            }
        }
        else if (conditions.Any != null && conditions.Any.Any())
        {
            sb.AppendLine("            conditionMet = false;");
            foreach (var condition in conditions.Any)
            {
                GenerateConditionEvaluation(sb, condition);
                sb.AppendLine("            if (conditionMet) break;");
            }
        }
    }

    private void GenerateConditionEvaluation(StringBuilder sb, Condition condition)
    {
        switch (condition)
        {
            case ComparisonCondition comp:
                sb.AppendLine($"            if (!data.TryGetValue(\"{comp.DataSource}\", out var value))");
                sb.AppendLine("            {");
                sb.AppendLine($"                _logger.Warning(\"Data source {comp.DataSource} not found\");");
                sb.AppendLine("                conditionMet = false;");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
                sb.AppendLine($"            conditionMet = value {comp.Operator} {comp.Value};");
                break;

            case ThresholdOverTimeCondition threshold:
                sb.AppendLine($"            var thresholdResult = await _dataStore.CheckThresholdOverTimeAsync(");
                sb.AppendLine($"                \"{threshold.DataSource}\",");
                sb.AppendLine($"                {threshold.Threshold},");
                sb.AppendLine($"                TimeSpan.FromMilliseconds({threshold.DurationMs}));");
                sb.AppendLine("            conditionMet = thresholdResult;");
                break;

            case ExpressionCondition expr:
                sb.AppendLine($"            // TODO: Implement expression evaluation");
                sb.AppendLine("            conditionMet = false;");
                break;
        }
    }

    private void GenerateActionCode(StringBuilder sb, RuleAction action)
    {
        sb.AppendLine($"                await _actionExecutor.ExecuteAsync(new CompiledRuleAction");
        sb.AppendLine("                {");
        if (action.SetValue != null)
        {
            sb.AppendLine("                    SetValue = new SetValueAction");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Key = \"{action.SetValue.Key}\",");
            if (!string.IsNullOrEmpty(action.SetValue.ValueExpression))
            {
                sb.AppendLine($"                        ValueExpression = \"{action.SetValue.ValueExpression}\"");
            }
            else
            {
                sb.AppendLine($"                        Value = {action.SetValue.Value}");
            }
            sb.AppendLine("                    }");
        }
        else if (action.SendMessage != null)
        {
            sb.AppendLine("                    SendMessage = new SendMessageAction");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Channel = \"{action.SendMessage.Channel}\",");
            sb.AppendLine($"                        Message = \"{action.SendMessage.Message}\"");
            sb.AppendLine("                    }");
        }
        sb.AppendLine("                });");
    }
}
